import {
  jarvisApi,
  type AgentEvent,
  type BackgroundTask,
  type BackgroundTaskDay,
  type CalendarEvent,
  type JarvisPlan,
  type JarvisPlanDay,
  type MaxwellWorkbenchItem,
  type MaxwellRescheduleRequest,
  type MaxwellRescheduleResult,
  type PendingAction,
  type PlanDayBulkUpdateResult,
  type PlannerCalendarResponse,
  type PlannerDailyMaintenanceResult,
  type PlannerOverdueMissedResult,
  type PlannerTaskCleanupResult,
  type PlannerTaskItem,
  type ProjectPlanCalendarResult,
  type SecretaryPlanRequest,
  type SecretaryPlanResult,
  type PlanMergeResult,
  type PlanSplitResult,
  type PlanWritePayload,
} from './jarvisApi'

export type {
  AgentEvent,
  BackgroundTask,
  BackgroundTaskDay,
  CalendarEvent,
  JarvisPlan,
  JarvisPlanDay,
  MaxwellWorkbenchItem,
  MaxwellRescheduleRequest,
  MaxwellRescheduleResult,
  PendingAction,
  PlanDayBulkUpdateResult,
  PlannerCalendarItem,
  PlannerConflict,
  PlannerDailyMaintenanceResult,
  PlannerFreeWindow,
  PlannerOverdueMissedResult,
  PlannerTaskCleanupResult,
  PlannerTaskItem,
  ProjectPlanCalendarResult,
  SecretaryPlanRequest,
  SecretaryPlanResult,
  PlanMergeResult,
  PlanSplitResult,
  PlanWritePayload,
} from './jarvisApi'

export type CalendarEventPayload = Parameters<typeof jarvisApi.addCalendarEvent>[0]
export type CalendarEventPatch = Parameters<typeof jarvisApi.updateCalendarEvent>[1]

export const jarvisScheduleApi = {
  getLocalLife: (force = false): Promise<any> => jarvisApi.getLocalLife(force),
  listCalendarEvents: (hoursAhead?: number, range?: { start: string; end: string }): Promise<CalendarEvent[]> => jarvisApi.listCalendarEvents(hoursAhead, range),
  addCalendarEvent: (payload: CalendarEventPayload): ReturnType<typeof jarvisApi.addCalendarEvent> => jarvisApi.addCalendarEvent(payload),
  deleteCalendarEvent: (eventId: string): Promise<void> => jarvisApi.deleteCalendarEvent(eventId),
  updateCalendarEvent: (eventId: string, patch: CalendarEventPatch): ReturnType<typeof jarvisApi.updateCalendarEvent> => jarvisApi.updateCalendarEvent(eventId, patch),

  listPendingActions: (): Promise<PendingAction[]> => jarvisApi.listPendingActions(),
  confirmPendingAction: (actionId: string): ReturnType<typeof jarvisApi.confirmPendingAction> => jarvisApi.confirmPendingAction(actionId),
  cancelPendingAction: (actionId: string): Promise<PendingAction> => jarvisApi.cancelPendingAction(actionId),
  updatePendingAction: (actionId: string, payload: Parameters<typeof jarvisApi.updatePendingAction>[1]): Promise<PendingAction> => jarvisApi.updatePendingAction(actionId, payload),

  listBackgroundTasks: (status?: string): Promise<BackgroundTask[]> => jarvisApi.listBackgroundTasks(status),
  updateBackgroundTask: (taskId: string, payload: Parameters<typeof jarvisApi.updateBackgroundTask>[1]): Promise<BackgroundTask> => jarvisApi.updateBackgroundTask(taskId, payload),
  listBackgroundTaskDays: (params?: Parameters<typeof jarvisApi.listBackgroundTaskDays>[0]): Promise<BackgroundTaskDay[]> => jarvisApi.listBackgroundTaskDays(params),
  completeBackgroundTaskDay: (dayId: string): Promise<BackgroundTaskDay> => jarvisApi.completeBackgroundTaskDay(dayId),
  deleteBackgroundTaskDay: (dayId: string): Promise<BackgroundTaskDay> => jarvisApi.deleteBackgroundTaskDay(dayId),

  listPlans: (status?: string): Promise<JarvisPlan[]> => jarvisApi.listPlans(status),
  createPlan: (payload: PlanWritePayload): Promise<JarvisPlan> => jarvisApi.createPlan(payload),
  updatePlan: (planId: string, payload: Partial<PlanWritePayload>): Promise<JarvisPlan> => jarvisApi.updatePlan(planId, payload),
  cancelPlan: (planId: string): Promise<JarvisPlan> => jarvisApi.cancelPlan(planId),
  deletePlan: (planId: string): Promise<JarvisPlan> => jarvisApi.deletePlan(planId),
  mergePlans: (payload: Parameters<typeof jarvisApi.mergePlans>[0]): Promise<PlanMergeResult> => jarvisApi.mergePlans(payload),
  splitPlan: (planId: string, payload: Parameters<typeof jarvisApi.splitPlan>[1]): Promise<PlanSplitResult> => jarvisApi.splitPlan(planId, payload),
  projectPlanToCalendar: (planId: string): Promise<ProjectPlanCalendarResult> => jarvisApi.projectPlanToCalendar(planId),
  listPlanEvents: (planId: string): Promise<AgentEvent[]> => jarvisApi.listPlanEvents(planId),

  listPlanDays: (params?: Parameters<typeof jarvisApi.listPlanDays>[0]): Promise<JarvisPlanDay[]> => jarvisApi.listPlanDays(params),
  completePlanDay: (dayId: string): Promise<JarvisPlanDay> => jarvisApi.completePlanDay(dayId),
  deletePlanDay: (dayId: string): Promise<JarvisPlanDay> => jarvisApi.deletePlanDay(dayId),
  updatePlanDay: (dayId: string, payload: Parameters<typeof jarvisApi.updatePlanDay>[1]): Promise<JarvisPlanDay> => jarvisApi.updatePlanDay(dayId, payload),
  movePlanDay: (dayId: string, payload: Parameters<typeof jarvisApi.movePlanDay>[1]): Promise<JarvisPlanDay> => jarvisApi.movePlanDay(dayId, payload),
  bulkUpdatePlanDays: (payload: Parameters<typeof jarvisApi.bulkUpdatePlanDays>[0]): Promise<PlanDayBulkUpdateResult> => jarvisApi.bulkUpdatePlanDays(payload),

  listPlannerTasks: (params?: Parameters<typeof jarvisApi.listPlannerTasks>[0]): Promise<PlannerTaskItem[]> => jarvisApi.listPlannerTasks(params),
  cleanupDuplicatePlannerTasks: (apply = false): Promise<PlannerTaskCleanupResult> => jarvisApi.cleanupDuplicatePlannerTasks(apply),
  runPlannerDailyMaintenanceOnce: (payload?: Parameters<typeof jarvisApi.runPlannerDailyMaintenanceOnce>[0]): Promise<PlannerDailyMaintenanceResult> => jarvisApi.runPlannerDailyMaintenanceOnce(payload),
  markOverduePlannerDaysMissed: (today?: string): Promise<PlannerOverdueMissedResult> => jarvisApi.markOverduePlannerDaysMissed(today),
  getPlannerCalendar: (range: Parameters<typeof jarvisApi.getPlannerCalendar>[0]): Promise<PlannerCalendarResponse> => jarvisApi.getPlannerCalendar(range),
  createSecretaryPlan: (payload: SecretaryPlanRequest): Promise<SecretaryPlanResult> => jarvisApi.createSecretaryPlan(payload),

  listMaxwellWorkbenchItems: (params?: Parameters<typeof jarvisApi.listMaxwellWorkbenchItems>[0]): Promise<MaxwellWorkbenchItem[]> => jarvisApi.listMaxwellWorkbenchItems(params),
  requestMaxwellReschedule: (payload: MaxwellRescheduleRequest): Promise<MaxwellRescheduleResult> => jarvisApi.requestMaxwellReschedule(payload),
  pushDailyTasksToMaxwellWorkbench: (planDate?: string): Promise<{ plan_date: string; pushed_count: number; items: MaxwellWorkbenchItem[] }> => jarvisApi.pushDailyTasksToMaxwellWorkbench(planDate),
}
